### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by KirbyBroderick** [ulissigroup/catlas#35]

**Comment by KirbyBroderick** [comment]
This will start a new cache, so I started https://github.com/ulissigroup/catlas/tree/documentation_update

**Comment by brookwander** [comment]
Some functions dont get used or are in odd files (check_if_memorized, cache_if_not_cached, load_cache)? Maybe pop_atoms?

**Comment by KirbyBroderick** [comment]
Also restructure repo in a more logical way

**Comment by KirbyBroderick** [comment]
freed at last by https://github.com/ulissigroup/catlas/pull/153
