### ISSUE TITLE
Commenting breaks all the tests??

### ISSUE THREAD

**Issue by KirbyBroderick** [ulissigroup/catlas#40]
https://github.com/ulissigroup/catlas/commits/KirbyBroderick-patch-2
https://github.com/ulissigroup/catlas/commit/d5f92cb7dd94a8a1e0720f861b9060f0cbf3cb86

I have no idea how this happened.

**Comment by zulissi** [comment]
Can this be closed now?

**Comment by KirbyBroderick** [comment]
We'll see if it crops up again during the documentation fix
