### ISSUE TITLE
Clean up shared-scratch

### ISSUE THREAD

**Issue by KirbyBroderick** [ulissigroup/catlas#59]
There are a lot of catlas-related folders in top-level shared-scratch. Should figure out which of these are still used, put those in catlas and update their paths in catlas code, and remove the rest.

**Comment by brookwander** [comment]
@KirbyBroderick is this done?

**Comment by brookwander** [comment]
Lets chat about this with @zulissi - do you have some suggestions for how to do this easily? Kirby is saying it slows the cluster to clean this up using rm commands

**Comment by zulissi** [comment]
I would suggest doing it at night when others won't notice the key. I don't know of a clean way to do this, but googling "cephfs delete large folders" or something like that is probably what I would do to get more suggestions.
