### ISSUE TITLE
Merge operation costly and unnecessary (adsorbate df + bulk df)

### ISSUE THREAD

**Issue by brookwander** [ulissigroup/catlas#7]
I think things could be reorganized to avoid this operation. It seems like a pinch point for the workflow (perhaps unsurprisingly)

**Comment by zulissi** [comment]
Can this be closed?

**Comment by KirbyBroderick** [comment]
@brookwander I think so. Most of the time seems to be spent enumerating and repartitioning

**Comment by brookwander** [comment]
confirmed. This was a problem when the workflow was using dask df rather than bag!
