### ISSUE TITLE
Have shifter pull latest stable catlas image on successful push?

### ISSUE THREAD

**Issue by KirbyBroderick** [ulissigroup/catlas#88]

**Comment by brookwander** [comment]
Seems to me this already happens? Or that simply appending `:latest`  to https://github.com/ulissigroup/catlas/blob/main/configs/dask_cluster/perlmutter/catlas_run.sh#L7 will make it happen. Any reason we are holding an issue for this? 

https://docs.nersc.gov/development/shifter/how-to-use/

**Comment by brookwander** [comment]
This seems like its not a priority
